//! Diagnostic-only tool, not part of the proxy itself: dumps
//! `zwp_linux_dmabuf_v1` and `zwp_linux_buffer_params_v1`'s own
//! request/event signature tables (as generated by wayland-scanner from
//! the real upstream XML) straight from the compiled-in `Interface`
//! data -- no live connection needed.
//!
//! Built while implementing ADR-0006's dmabuf `create_immed()` path
//! (docs/adr/adr-0006-recreate-buffers-via-fd-handover.md): the ADR's own
//! sketch of `add()`/`create_immed()`'s argument order was written from
//! memory, not from checking the actual generated tables -- this exists
//! so that check is a `cargo run`, not a guess, matching this project's
//! own "verify, don't guess" discipline. Kept as a permanent tool (not a
//! throwaway script) since the same question -- "what's this request's
//! exact wire signature and opcode" -- comes up for every new
//! `Recreatable` variant this project adds.
//!
//! Usage: `cargo run --example probe_dmabuf`

use wayland_backend::protocol::Interface;

fn dump(interface: &Interface) {
    println!("== {} (v{}) requests ==", interface.name, interface.version);
    for (i, r) in interface.requests.iter().enumerate() {
        println!(
            "  {i}: {}{} sig={:?}{}",
            r.name,
            if r.is_destructor { " [destructor]" } else { "" },
            r.signature,
            r.child_interface.map(|c| format!(" -> {}", c.name)).unwrap_or_default(),
        );
    }
    println!("== {} events ==", interface.name);
    for (i, r) in interface.events.iter().enumerate() {
        println!("  {i}: {} sig={:?}", r.name, r.signature);
    }
}

fn main() {
    use wayland_protocols::wp::linux_dmabuf::zv1::client::__interfaces as linux_dmabuf;

    let dmabuf = &linux_dmabuf::ZWP_LINUX_DMABUF_V1_INTERFACE;
    dump(dmabuf);

    let params = dmabuf
        .requests
        .iter()
        .find(|r| r.name == "create_params")
        .and_then(|r| r.child_interface)
        .expect("create_params always has a static child interface");
    println!();
    dump(params);
}
